#image:
#file: .gitpod.Dockerfile
image: kavis131995/gitpod_mlmodel


ports:
- port: 8080
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
  
  

tasks:
- init: >
    source activate py36 && pip install jupyterlab  &&
    source activate py36 && pip install -r requirements.txt  &&
    source activate py36 && pip install -r requirements_fake.txt  &&
    source activate py36 && pip install -e .  --no-deps  &&
    source activate py36 && pip install  ipykernel   


